name: Build
run-name: Build Tests (${{ github.actor }})
on: [push]
jobs:
  security-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: NPM audit
        working-directory: insecure
        run: npm audit
  run-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run ESLint
        working-directory: mashup
        run: |
          npm install
          npm run lint
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Jest test
        working-directory: unittesting
        run: |
          npm install
          npm run test
